apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-webapp-prod
  namespace: argocd
  labels:
    tier: production
spec:
  project: default
  source:
    repoURL: https://github.com/PyaePhyoKanto/my-gitops-repo.git
    targetRevision: HEAD
    path: charts/my-webapp
    helm:
      valueFiles:
        - ../../environments/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true